// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_h4zac6wzfpVRVrwHTvUGx-QdXAtD9g0',
    appId: '1:542684512401:web:f16a5c8120f91276177f30',
    messagingSenderId: '542684512401',
    projectId: 'parking-express-27f82',
    authDomain: 'parking-express-27f82.firebaseapp.com',
    databaseURL: 'https://parking-express-27f82-default-rtdb.firebaseio.com',
    storageBucket: 'parking-express-27f82.appspot.com',
    measurementId: 'G-L3LF0XY8SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFC-mwfyniSTZrDsq6vZKex6A6anMmDqA',
    appId: '1:542684512401:android:959a1264147c0799177f30',
    messagingSenderId: '542684512401',
    projectId: 'parking-express-27f82',
    databaseURL: 'https://parking-express-27f82-default-rtdb.firebaseio.com',
    storageBucket: 'parking-express-27f82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDrJ371bwEHw5ZP_vpW31noRmqQVZi3A',
    appId: '1:542684512401:ios:4ad642ff04a534e5177f30',
    messagingSenderId: '542684512401',
    projectId: 'parking-express-27f82',
    databaseURL: 'https://parking-express-27f82-default-rtdb.firebaseio.com',
    storageBucket: 'parking-express-27f82.appspot.com',
    iosBundleId: 'com.aries.parkingexpressMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDrJ371bwEHw5ZP_vpW31noRmqQVZi3A',
    appId: '1:542684512401:ios:6fb1082f9eccc85b177f30',
    messagingSenderId: '542684512401',
    projectId: 'parking-express-27f82',
    databaseURL: 'https://parking-express-27f82-default-rtdb.firebaseio.com',
    storageBucket: 'parking-express-27f82.appspot.com',
    iosBundleId: 'com.aries.parkingexpressMobile.RunnerTests',
  );
}
